#!/bin/sh

BIN_DIR=`dirname "$0"`
if [ "$BIN_DIR" = '.' ]; then
    BIN_DIR=`pwd`
fi

APP=com.alteredmechanism.classversionextractor.ClassVersionExtractor
CLASSES_DIR="$HOME"/git/classver/build/classes/main
MAIN_CLASS_FILE=${APP//.//}.class

if [ -f "$CLASSES_DIR/$MAIN_CLASS_FILE" ]
then
    exec java -cp "$CLASSES_DIR" $APP "$@"
else
    exec java -jar `dirname "$BIN_DIR"`/lib/`basename "$0"`.jar "$@"
fi

