#!/bin/sh

BIN_DIR=`dirname "$0"`
if [ "$BIN_DIR" = '.' ]; then
    BIN_DIR=`pwd`
fi

CLASSES_DIR="$HOME"/src/classver/build/classes
MAIN_CLASS=com.alteredmechanism.classversionextractor.ClassVersionExtractor
MAIN_CLASS_FILE=${MAIN_CLASS_FILE//.//}.class

if [ -f "$CLASSES_DIR/$MAIN_CLASS_FILE" ]
then
    exec java -cp "$CLASSES_DIR" $MAIN_CLASS "$@"
else
    exec java -jar `dirname "$BIN_DIR"`/lib/`basename "$0"`.jar "$@"
fi

